### ISSUE TITLE
`getItemPosition` should override `POSITION_UNCHANGED` to `POSITION_NONE` in RTL mode

### ISSUE THREAD

**Issue by DavidDTA** [diego-gomez-olvera/RtlViewPager#2]
Adding items to the end of the collection adds them to the beginning of the `ViewPager`.  Items whose positions do not change from the view of the wrapped adapter actually do change from the perspective of the `ViewPager`.

This causes crashes in the case were the adapter wraps a list of views, `instantiateItem` adds the view to the container, and `destroyItem` removes it.  Start with 1 view in RTL mode.  After adding a second view to the end and calling `notifyDataSetChanged`, the `ViewPager` keeps the first view since its position is reported as unchanged.  It then attempts to add an additional page offscreen in preparation for scrolling.  This page is item 1 according to the `ViewPager` and item 0 according to the wrapped adapter.  This causes the already-added view to be re-added, causing a crash.

**Comment by diego-gomez-olvera** [comment]
Hi @hospitalitarian. I think replacement for POSITION_UNCHANGED would be the item current position swapped instead of POSITION_NONE (that should be used when the item is no longer present in the adapter). I tried to apply your solution and mine, but I am facing issues. Could you provide more information about your solution?

**Comment by DavidDTA** [comment]
I am not currently using this library.  The code in our version looks like this:

```
@Override
public int getItemPosition(Object object) {
    int position = mAdapter.getItemPosition(object);
    if (isRTL()) {
        if (position == POSITION_UNCHANGED || position == POSITION_NONE) {
            // We can't accept POSITION_UNCHANGED when in RTL mode because adding items to the end of the collection adds them to the beginning of the
            // ViewPager.  Items whose positions do not change from the perspective of the wrapped adapter actually do change from the perspective of
            // the ViewPager.
            position = POSITION_NONE;
        } else {
            position = getCount() - position - 1;
        }
    }
    return position;
}
```

**Comment by diego-gomez-olvera** [comment]
The code that I have right now applying that change does not behave as expected (adding a new item while being in the page to the right end changes the currently selected items). Did you also tune setCurrentItem()?

If your code is inside ReverseAdapter you should not need isRTL() checks, as it will always be true.

**Comment by DavidDTA** [comment]
Our implementation doesn't use a reversing adapter.

```
@Override
public void setCurrentItem(int position, boolean smoothScroll) {
    PagerAdapter adapter = super.getAdapter();
    if (adapter != null && isRTL()) {
        position = adapter.getCount() - position - 1;
    }
    super.setCurrentItem(position, smoothScroll);
}

@Override
public void setCurrentItem(int position) {
    PagerAdapter adapter = super.getAdapter();
    if (adapter != null && isRTL()) {
        position = adapter.getCount() - position - 1;
    }
    super.setCurrentItem(position);
}
```

This code is all inside the ViewPager, not the adapter.

**Comment by DavidDTA** [comment]
I misspoke.  We do use a reversing adapter, but the code is in the ViewPager.
